Fix string joining (#23)
* v2.1.1

* bug fix in joining arrays

* fix diff test

* remove dist

* add concatenation check

---------

Co-authored-by: kamil.rybacki <kamil.rybacki@pg.edu.pl>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -79,6 +79,13 @@ jobs:
           exit 1
         fi
         echo "Files found: ${{ steps.diff-cache.outputs.files }}"
+    - name: Check if there are commas present due to bad concatenation
+      run: |
+        if [[ "${{ steps.diff-cache.outputs.files }}" == *","* ]]; then
+          echo "Commas found. Check index.ts for concatenation errors."
+          exit 1
+        fi
+        echo "No commas found"
 
   post-action-tests:
     runs-on: ubuntu-latest
